# General Script

In [1]:
import pandas as pd

LAB3_PATH = r"C:\Users\cathe\Downloads\Lab 3 - 2026-07-02 Comma delimited CSV.csv"
GROUP1_PATH = r"C:\Users\cathe\Downloads\study_group_1.csv"
GROUP2_PATH = r"C:\Users\cathe\Downloads\study_group_2.csv"
OUTPUT_PATH = r"C:\Users\cathe\Documents\Github\remind\Analysis\Lab 3 - 2026-07-02 with study group.csv"

In [2]:
def normalize_email(email):
    return str(email).strip().lower()

We first add a column to the assignment CSV indicating whether each student belongs to Study Group 1, Study Group 2.

In [3]:
lab3 = pd.read_csv(LAB3_PATH)
group1_emails = set(pd.read_csv(GROUP1_PATH)["email"].map(normalize_email))
group2_emails = set(pd.read_csv(GROUP2_PATH)["email"].map(normalize_email))

lab3.head()

,SID,Email,Sections,Total Score,Max Points,Status,Submission ID,Submission Time,Lateness (H:M:S),View Count,Submission Count,1: Autograder (1.0 pts)
0,3.042833e+09,matthewrib@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418008583.0,7/1/2026 11:20,0:00:00,0.0,1.0,0.0
1,3.043132e+09,iriswen@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418009409.0,7/1/2026 11:39,0:00:00,0.0,1.0,0.0
2,3.043183e+09,chenzixin24@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418009429.0,7/1/2026 11:40,0:00:00,0.0,1.0,0.0
3,3.043145e+09,imnotsuri@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418009873.0,7/1/2026 11:46,0:00:00,0.0,1.0,0.0
4,3.043104e+09,kellychenghq@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418010788.0,7/1/2026 12:02,0:00:00,0.0,1.0,0.0

In [6]:
def assign_group(email):
    email = normalize_email(email)
    in_group1 = email in group1_emails
    in_group2 = email in group2_emails
    if in_group1:
        return "Group 1"
    if in_group2:
        return "Group 2"
    return "None"


lab3["Study Group"] = lab3["Email"].map(assign_group)
lab3.head()

,SID,Email,Sections,Total Score,Max Points,Status,Submission ID,Submission Time,Lateness (H:M:S),View Count,Submission Count,1: Autograder (1.0 pts),Study Group
0,3.042833e+09,matthewrib@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418008583.0,7/1/2026 11:20,0:00:00,0.0,1.0,0.0,Group 2
1,3.043132e+09,iriswen@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418009409.0,7/1/2026 11:39,0:00:00,0.0,1.0,0.0,Group 2
2,3.043183e+09,chenzixin24@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418009429.0,7/1/2026 11:40,0:00:00,0.0,1.0,0.0,Group 2
3,3.043145e+09,imnotsuri@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418009873.0,7/1/2026 11:46,0:00:00,0.0,1.0,0.0,Group 2
4,3.043104e+09,kellychenghq@berkeley.edu,"COMPSCI 61A LEC 001 (In Person), COMPSCI 61A D...",0.0,1,Graded,418010788.0,7/1/2026 12:02,0:00:00,0.0,1.0,0.0,Group 2

In [7]:
lab3["Study Group"].value_counts()

Study Group
Group 2    80
Group 1    75
None       60
Name: count, dtype: int64

In [8]:
lab3.to_csv(OUTPUT_PATH, index=False)
print(f"Wrote {len(lab3)} rows to {OUTPUT_PATH}")

Wrote 215 rows to C:\Users\cathe\Documents\Github\remind\Analysis\Lab 3 - 2026-07-02 with study group.csv